CREATE TABLE web.terminals (
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  type VARCHAR DEFAULT 'terminal',
  latitude REAL NOT NULL,
  longitude REAL NOT NULL,
  owner_id INT REFERENCES web.companies(id),
  operator_id INT REFERENCES web.companies(id),
  operational BOOLEAN,
  terminaling_capacity INT,
  storage_capacity INT,
  pipeline_access web.access,
  rail_access web.access,
  truck_access web.access,
  marine_access web.access,
  truck_bays INT,
  rack_capacity INT,
  tanks INT,
  contact_name VARCHAR,
  contact_phone VARCHAR,
  contact_fax VARCHAR,
  contact_role VARCHAR,
  contact_email VARCHAR,
  street VARCHAR,
  city VARCHAR,
  state CHAR(2),
  zip VARCHAR(5),
  FOREIGN KEY (id, type) REFERENCES web.locations (ref_id, type) MATCH FULL
);
