#!/usr/bin/env node

const commander = require('commander');

const categories = require('./categories');
const products = require('./products');
const grades = require('./grades');
const companies = require('./companies');
const refineries = require('./refineries');
const terminals = require('./terminals');

commander
  .version('0.1.0')
  .option('-a, --all', 'Run all seed files')
  .option('-l, --locations', 'Seed refineries and terminals')
  .option('-r, --refineries', 'Seed refineries')
  .option('-t, --terminals', 'Seed terminals')
  .option('-p, --pipelines', 'Seed pipelines')
  .parse(process.argv);

if (commander.all) {
  categories.seed();
  products.seed();
  grades.seed();
  companies.seed();
  refineries.seed();
  terminals.seed();
  process.nextTick(process.exit);
}
if (commander.locations) {
  refineries.seed();
  terminals.seed();
  process.nextTick(process.exit);
}
if (commander.refineries) {
  refineries.seed();
  process.nextTick(process.exit);
}
if (commander.terminals) {
  terminals.seed();
  process.nextTick(process.exit);
}
if (commander.pipelines) {
  pipelines.seed();
  process.nextTick(process.exit);
}