const Handlers = require('./handlers');

module.exports = [{
  method: 'GET',
  path: '/locations',
  handler: Handlers.getLocations,
}, {
  method: 'GET',
  path: '/refineries',
  handler: Handlers.getRefineries,
}, {
  method: 'GET',
  path: '/refineries/{id}',
  handler: Handlers.getRefinery,
}, {
  method: 'GET',
  path: '/terminals',
  handler: Handlers.getTerminals,
}, {
  method: 'GET',
  path: '/terminals/{id}',
  handler: Handlers.getTerminal,
}, {
  method: 'GET',
  path: '/terminals/{t_id}/grades/{g_id}/movements',
  handler: Handlers.getTerminalMovements,
}, {
  method: 'GET',
  path: '/terminals/{t_id}/grades/{g_id}/rundowns',
  handler: Handlers.getTerminalRundowns,
}, {
  method: 'GET',
  path: '/terminals/{t_id}/grades/{g_id}/forecasts/rundowns',
  handler: Handlers.getTerminalForecastRundowns,
}, {
  method: 'GET',
  path: '/terminals/{t_id}/grades/{g_id}/inventory',
  handler: Handlers.getTerminalInventory
}, {
  method: 'GET',
  path: '/terminals/{t_id}/overages',
  handler: Handlers.getTerminalOverages
}, {
  method: 'GET',
  path: '/terminals/{t_id}/shortages',
  handler: Handlers.getTerminalShortages
}, {
  method: 'GET',
  path: '/terminals/{t_id}/warnings',
  handler: Handlers.getTerminalWarnings
}, {
  method: 'GET',
  path: '/pipelines',
  handler: Handlers.getPipelines,
}, {
  method: 'GET',
  path: '/pipelines/{id}',
  handler: Handlers.getPipeline,
}, {
  method: 'GET',
  path: '/segments',
  handler: Handlers.getSegments,
}, {
  method: 'GET',
  path: '/segments/{id}',
  handler: Handlers.getSegment,
}, {
  method: 'GET',
  path: '/stations',
  handler: Handlers.getStations,
}, {
  method: 'GET',
  path: '/stations/{id}',
  handler: Handlers.getStation,
}, {
  method: 'GET',
  path: '/neighbors/{type}/{id}',
  handler: Handlers.getNeighbors,
}];
