-- Static
CREATE TABLE web.terminals (
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  type VARCHAR DEFAULT 'terminal',
  latitude REAL NOT NULL,
  longitude REAL NOT NULL,
  owner_id INT REFERENCES web.companies(id) NOT NULL,
  operator_id INT REFERENCES web.companies(id) NOT NULL,
  operational BOOLEAN NOT NULL DEFAULT FALSE,
  terminaling_capacity INT CHECK (terminaling_capacity >= 0),
  storage_capacity INT CHECK (storage_capacity >= 0),
  pipeline_access web.access,
  rail_access web.access,
  truck_access web.access,
  marine_access web.access,
  truck_bays INT CHECK (truck_bays >= 0),
  rack_capacity INT CHECK (rack_capacity >= 0),
  contact_name VARCHAR,
  contact_phone VARCHAR,
  contact_fax VARCHAR,
  contact_role VARCHAR,
  contact_email VARCHAR,
  street VARCHAR,
  city VARCHAR,
  state CHAR(2),
  zip VARCHAR(5),
  FOREIGN KEY (id, type) REFERENCES web.locations (ref_id, type) MATCH FULL
);
